# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2025 Univention GmbH

[project]
name = "selfservice-listener"
version = "0.1.0"
description = "Univention Management Stack - Selfservice Listener"
readme = "README.md"
authors = [
    { name = "Univention GmbH", email = "packages@univention.de" },
]
license = "AGPL-3.0-only"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.0",
    "anyio>=4.3.0",
    "nubus-provisioning-consumer==0.42.0",
    "pydantic>=2.3.0",
    "pydantic-settings>=2.0.3",
]

[project.scripts]
selfservice-listener = "invitation.__main__:main"

[dependency-groups]
dev = [
    "pytest>=7.4.2",
    "pytest-cov>=4.1",
]

[tool.uv]
package = true

[tool.uv.sources]
nubus-provisioning-consumer = { index = "ucs" }

[[tool.uv.index]]
name = "ucs"
url = "https://git.knut.univention.de/api/v4/projects/882/packages/pypi/simple"
explicit = true
default = false

[tool.hatch.build.targets.wheel]
packages = ["invitation"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]  # activate isort

[tool.ruff.lint.isort]
known-first-party = ["univention"]
